# Copyright (c) 2022 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//BnesBrowser/browser/sources.gni")
import("//BnesBrowser/browser/updater/buildflags.gni")
import("//BnesBrowser/build/config.gni")
import("//BnesBrowser/components/local_ai/buildflags/buildflags.gni")
import("//BnesBrowser/ui/webui/custom_profile_image_config.gni")
import("//build/buildflag_header.gni")
import("//build/config/features.gni")
import("//chrome/common/features.gni")

buildflag_header("sparkle_buildflags") {
  header = "sparkle_buildflags.h"
  flags = [ "ENABLE_SPARKLE=$enable_sparkle" ]
}

if (enable_sparkle && !build_sparkle) {
  bundle_data("prebuilt_sparkle_framework_bundle_data") {
    sources = [ "//build/mac_files/sparkle_binaries/Sparkle.framework" ]
    outputs = [ "{{bundle_contents_dir}}/Frameworks/{{source_file_part}}" ]
  }
}

source_set("browser_process") {
  visibility = [
    "//BnesBrowser/browser/*",
    "//chrome/browser/*",
  ]

  sources = [ "brave_browser_process.h" ]

  deps = [
    "//BnesBrowser/browser/brave_stats:buildflags",
    "//BnesBrowser/components/brave_ads/buildflags",
    "//BnesBrowser/components/brave_vpn/common/buildflags",
    "//BnesBrowser/components/local_ai/buildflags",
    "//BnesBrowser/components/request_otr/common/buildflags",
    "//BnesBrowser/components/speedreader/common/buildflags",
    "//BnesBrowser/components/tor/buildflags",
    "//chrome/browser:browser_process",
    "//extensions/buildflags",
  ]

  if (enable_local_ai) {
    deps += [ "//BnesBrowser/components/local_ai/core" ]
  }
}

source_set("brave_global_features") {
  sources = [ "brave_global_features.h" ]

  public_deps = [
    "//chrome/browser:global_features",
    "//extensions/buildflags",
  ]
}

source_set("brave_global_features_impl") {
  visibility = [ "//BnesBrowser/browser:core" ]
  sources = [ "brave_global_features.cc" ]

  deps = [
    "//base",
    "//BnesBrowser/browser:brave_global_features",
    "//BnesBrowser/components/extension_malware_blocklist/common",
    "//chrome/browser:global_features",
    "//extensions/buildflags",
  ]

  if (enable_extensions) {
    deps += [ "//BnesBrowser/components/extension_malware_blocklist/browser" ]
  }
}

source_set("core") {
  visibility = [ "//chrome/browser" ]

  configs += [
    "//build/config/compiler:wexit_time_destructors",
    "//build/config:precompiled_headers",
  ]

  sources = brave_chrome_browser_sources
  deps = brave_chrome_browser_deps + [
           "//BnesBrowser/browser/ui:custom_profile_image_buildflags",
           "//BnesBrowser/browser/ui/window_feature_controller:chromium_impl",
           "//BnesBrowser/bnes:scheme_handler",
         ]
  if (enable_brave_custom_profile_image_webui) {
    deps += [ "//BnesBrowser/browser/ui/webui/custom_profile_image" ]
  }
  public_deps = brave_chrome_browser_public_deps +
                [ "//chrome/browser:browser_public_dependencies" ]
  allow_circular_includes_from =
      brave_chrome_browser_allow_circular_includes_from
}

group("browser") {
  visibility = [
    "//BnesBrowser:browser_dependencies",
    "//BnesBrowser/browser/*",
    "//BnesBrowser/components/brave_rewards/core/engine:headers",
    "//BnesBrowser/test:*",

    # these are layering violation and need to be fixed
    "//BnesBrowser/components/brave_rewards/content:testutil",
    "//BnesBrowser/components/brave_rewards/test:brave_rewards_unit_tests",
  ]

  if (enable_sparkle) {
    if (build_sparkle) {
      deps = [ "//BnesBrowser/vendor/sparkle:sparkle_framework_bundle_data" ]
    } else {
      deps = [ ":prebuilt_sparkle_framework_bundle_data" ]
    }
  }

  # Group depending on upstream's counterpart to make it easier to manage
  # dependencies in brave/ (//chrome/browser does not depend on this target
  # so //BnesBrowser/browser becomes essentially an alias for //chrome/browser now).
  public_deps = [ "//chrome/browser" ]
}

source_set("unit_tests") {
  testonly = true

  sources = []
  deps = []

  if (is_win) {
    sources += [ "default_protocol_handler_utils_win_unittest.cc" ]

    deps += [
      "//base",
      "//BnesBrowser/browser",
      "//testing/gtest",
    ]
  }
}
