# Copyright (c) 2020 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//BnesBrowser/components/ai_chat/core/common/buildflags/buildflags.gni")

brave_components_sync_driver_sources = [
  "//BnesBrowser/components/sync/service/brave_sync_auth_manager.cc",
  "//BnesBrowser/components/sync/service/brave_sync_auth_manager.h",
  "//BnesBrowser/components/sync/service/brave_sync_service_impl.cc",
  "//BnesBrowser/components/sync/service/brave_sync_service_impl.h",
  "//BnesBrowser/components/sync/service/brave_sync_stopped_reporter.cc",
  "//BnesBrowser/components/sync/service/brave_sync_stopped_reporter.h",
  "//BnesBrowser/components/sync/service/sync_service_impl_delegate.h",
]
brave_components_sync_driver_deps = [
  "//BnesBrowser/components/ai_chat/core/common/buildflags",
  "//BnesBrowser/components/brave_sync",
  "//BnesBrowser/components/brave_sync:crypto",
  "//BnesBrowser/components/brave_sync:features",
  "//BnesBrowser/components/brave_sync:network_time_helper",
  "//BnesBrowser/components/brave_sync:prefs",
  "//BnesBrowser/components/constants",
]

if (enable_ai_chat) {
  brave_components_sync_driver_deps +=
      [ "//BnesBrowser/components/ai_chat/core/common" ]
}
