# Copyright (c) 2025 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//BnesBrowser/build/config.gni")
import("//BnesBrowser/components/brave_ads/buildflags/buildflags.gni")

assert(is_android)

source_set("new_tab_takeover") {
  sources = [
    "new_tab_takeover_ui.cc",
    "new_tab_takeover_ui.h",
    "new_tab_takeover_ui_config.cc",
    "new_tab_takeover_ui_config.h",
  ]

  deps = [
    "//base",
    "//BnesBrowser/components/brave_ads/buildflags",
    "//BnesBrowser/components/constants",
    "//BnesBrowser/components/new_tab_takeover:new_tab_takeover_generated_resources",
    "//BnesBrowser/components/ntp_background_images/browser",
    "//chrome/browser:browser_public_dependencies",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/ui/android/tab_model",
    "//content/public/browser",
    "//content/public/common",
    "//ui/webui",
    "//url",
  ]

  if (enable_brave_ads) {
    deps += [ "//BnesBrowser/browser/brave_ads" ]
  }

  public_deps = [
    "//BnesBrowser/browser/ntp_background",
    "//BnesBrowser/components/new_tab_takeover/mojom",
    "//BnesBrowser/components/ntp_background_images/browser/mojom",
    "//mojo/public/cpp/bindings",
  ]
}
