# Copyright (c) 2021 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

import("//BnesBrowser/components/psst/buildflags/buildflags.gni")

brave_components_content_settings_core_browser_sources = [
  "//BnesBrowser/components/content_settings/core/browser/brave_content_settings_browsing_data_utils.cc",
  "//BnesBrowser/components/content_settings/core/browser/brave_content_settings_browsing_data_utils.h",
  "//BnesBrowser/components/content_settings/core/browser/brave_content_settings_utils.cc",
  "//BnesBrowser/components/content_settings/core/browser/brave_content_settings_utils.h",
]

brave_components_content_settings_core_browser_deps = [
  "//base",
  "//BnesBrowser/components/brave_shields/core/common",
  "//BnesBrowser/components/brave_wallet/common/buildflags",
  "//BnesBrowser/components/content_settings/core/common",
  "//BnesBrowser/components/psst/buildflags",
  "//url",
]

if (!is_ios) {
  brave_components_content_settings_core_browser_sources += [
    "//BnesBrowser/components/content_settings/core/browser/brave_content_settings_pref_provider.cc",
    "//BnesBrowser/components/content_settings/core/browser/brave_content_settings_pref_provider.h",
    "//BnesBrowser/components/content_settings/core/browser/brave_global_value_map.cc",
    "//BnesBrowser/components/content_settings/core/browser/brave_global_value_map.h",
    "//BnesBrowser/components/content_settings/core/browser/remote_list_provider.cc",
    "//BnesBrowser/components/content_settings/core/browser/remote_list_provider.h",
  ]

  brave_components_content_settings_core_browser_deps += [
    "//BnesBrowser/components/constants",
    "//BnesBrowser/components/google_sign_in_permission",
    "//BnesBrowser/components/webcompat/content/browser",
    "//components/prefs",
    "//content/public/browser",
    "//net",
  ]
}

if (enable_psst) {
  brave_components_content_settings_core_browser_deps +=
      [ "//BnesBrowser/components/psst/core/common" ]
}
