browser_api_url_public_headers = [
  "//BnesBrowser/ios/browser/api/url/url_formatter.h",
  "//BnesBrowser/ios/browser/api/url/url_origin_ios.h",
  "//BnesBrowser/ios/browser/api/url/url_pattern_ios.h",
  "//BnesBrowser/ios/browser/api/url/url_spoof_checker.h",
  "//BnesBrowser/ios/browser/api/url/url_utils.h",
]
