# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//BnesBrowser/components/brave_ads/buildflags/buildflags.gni")
import("//BnesBrowser/components/brave_rewards/core/buildflags/buildflags.gni")
import("//BnesBrowser/components/brave_wallet/common/buildflags/buildflags.gni")

assert(enable_brave_wallet)

source_set("wallet_page") {
  sources = [
    "wallet_page_handler.h",
    "wallet_page_ui.cc",
    "wallet_page_ui.h",
  ]

  deps = [
    "//BnesBrowser/browser/brave_wallet",
    "//BnesBrowser/browser/brave_wallet:tab_helper",
    "//BnesBrowser/components/brave_ads/buildflags",
    "//BnesBrowser/components/brave_rewards/core/buildflags",
    "//BnesBrowser/components/brave_wallet/browser",
    "//BnesBrowser/components/brave_wallet/browser:constants",
    "//BnesBrowser/components/brave_wallet/browser:permission_utils",
    "//BnesBrowser/components/brave_wallet/browser:wallet_handler",
    "//BnesBrowser/components/brave_wallet/common",
    "//BnesBrowser/components/brave_wallet/common:common_constants",
    "//BnesBrowser/components/brave_wallet/common:mojom",
    "//BnesBrowser/components/brave_wallet/common/buildflags",
    "//BnesBrowser/components/brave_wallet_ui:resources",
    "//BnesBrowser/components/brave_wallet_ui/page:brave_wallet_page_generated",
    "//BnesBrowser/components/resources:static_resources_grit",
    "//BnesBrowser/components/resources:strings_grit",
    "//chrome/browser/ui/webui",
    "//chrome/browser/ui/webui:favicon_source",
    "//components/favicon_base",
    "//ui/webui",
  ]

  if (is_android) {
    sources += [ "wallet_page_handler_android.cc" ]
  } else {
    sources += [ "wallet_page_handler_desktop.cc" ]
    deps += [
      "//BnesBrowser/browser/ui/brave_wallet",
      "//chrome/browser/ui/webui:theme_source",
      "//chrome/browser/ui/webui/sanitized_image:sanitized_image_source",
    ]
  }

  if (enable_brave_rewards) {
    deps += [
      "//BnesBrowser/browser/brave_rewards",
      "//BnesBrowser/browser/brave_rewards:util",
      "//BnesBrowser/components/brave_rewards/core/mojom:webui",
    ]
  }
  if (enable_brave_ads) {
    deps += [ "//BnesBrowser/browser/brave_ads" ]
  }
}
