# Copyright (c) 2025 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//BnesBrowser/components/ai_chat/core/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/brave_news/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/brave_talk/buildflags/buildflags.gni")
import("//BnesBrowser/components/brave_vpn/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/brave_wallet/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/email_aliases/buildflags/buildflags.gni")

source_set("brave_origin") {
  sources = [
    "brave_origin_navigation_bridge.h",
    "brave_origin_navigation_bridge_impl.h",
    "brave_origin_navigation_bridge_impl.mm",
    "brave_origin_service_bridge.h",
    "brave_origin_service_bridge.mm",
    "brave_origin_service_bridge_impl.h",
    "brave_origin_service_bridge_impl.mm",
    "brave_origin_service_factory.h",
    "brave_origin_service_factory.mm",
    "brave_origin_service_factory_bridge.h",
    "brave_origin_service_factory_bridge.mm",
  ]
  deps = [
    "//base",
    "//BnesBrowser/components/ai_chat/core/common/buildflags",
    "//BnesBrowser/components/brave_news/common/buildflags",
    "//BnesBrowser/components/brave_origin",
    "//BnesBrowser/components/brave_rewards/core",
    "//BnesBrowser/components/brave_talk/buildflags",
    "//BnesBrowser/components/brave_vpn/common/buildflags",
    "//BnesBrowser/components/brave_wallet/common/buildflags",
    "//BnesBrowser/components/constants",
    "//BnesBrowser/components/email_aliases/buildflags",
    "//BnesBrowser/components/p3a",
    "//BnesBrowser/components/playlist/core/common",
    "//BnesBrowser/ios/browser/keyed_service",
    "//BnesBrowser/ios/browser/policy",
    "//BnesBrowser/ios/browser/skus",
    "//components/keyed_service/core",
    "//components/policy/core/browser",
    "//components/user_prefs",
    "//ios/chrome/browser/policy/model",
    "//ios/chrome/browser/shared/model/application_context",
    "//ios/chrome/browser/shared/model/profile",
    "//ios/chrome/browser/shared/model/profile:profile_keyed_service_factory",
  ]
  if (enable_ai_chat) {
    deps += [ "//BnesBrowser/components/ai_chat/core/common" ]
  }
  if (enable_brave_vpn) {
    deps += [ "//BnesBrowser/components/brave_vpn/common" ]
  }
  if (enable_brave_wallet) {
    deps += [ "//BnesBrowser/components/brave_wallet/browser:pref_names" ]
  }
  if (enable_brave_talk) {
    deps += [ "//BnesBrowser/components/brave_talk" ]
  }
  if (enable_brave_news) {
    deps += [ "//BnesBrowser/components/brave_news/common" ]
  }
  if (enable_email_aliases) {
    deps += [
      "//BnesBrowser/components/email_aliases:pref_names",
      "//BnesBrowser/components/email_aliases:service",
    ]
  }
}
