# Copyright (c) 2024 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

brave_content_browser_sources =
    [ "//BnesBrowser/content/browser/devtools/adblock_devtools_instrumentation.cc" ]

if (is_android) {
  brave_content_browser_sources += [
    "//BnesBrowser/content/browser/screen_orientation/brave_screen_orientation_delegate_android.cc",
    "//BnesBrowser/content/browser/screen_orientation/brave_screen_orientation_delegate_android.h",
  ]
}

brave_content_browser_deps = [
  "//BnesBrowser/components/ai_chat/core/common/buildflags",
  "//BnesBrowser/components/brave_service_keys",
  "//BnesBrowser/components/brave_shields/core/common:mojom",
  "//BnesBrowser/components/brave_wallet/common/buildflags",
  "//BnesBrowser/components/speech_to_text",
]
