# Copyright (c) 2025 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//BnesBrowser/components/ai_chat/core/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/brave_education/buildflags.gni")
import("//BnesBrowser/components/brave_rewards/core/buildflags/buildflags.gni")
import("//BnesBrowser/components/brave_vpn/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/brave_wallet/common/buildflags/buildflags.gni")
import("//mojo/public/tools/bindings/mojom.gni")

assert(!is_android)

mojom("mojom") {
  sources = [ "brave_welcome_page.mojom" ]
}

source_set("brave_welcome_page") {
  sources = [
    "brave_welcome_page_prefs.cc",
    "brave_welcome_page_prefs.h",
    "brave_welcome_page_ui.cc",
    "brave_welcome_page_ui.h",
    "welcome_page_features.cc",
    "welcome_page_features.h",
    "welcome_page_handler.cc",
    "welcome_page_handler.h",
  ]

  public_deps = [
    ":mojom",
    "//chrome/browser/themes",
    "//components/prefs",
    "//ui/webui/resources/cr_components/theme_color_picker:mojom",
  ]

  deps = [
    "//base",
    "//BnesBrowser/browser/resources/brave_welcome_page:generated_resources",
    "//BnesBrowser/browser/ui:brave_tab_prefs",
    "//BnesBrowser/components/ai_chat/core/common/buildflags",
    "//BnesBrowser/components/brave_education",
    "//BnesBrowser/components/brave_education:buildflags",
    "//BnesBrowser/components/brave_rewards/core",
    "//BnesBrowser/components/brave_rewards/core/buildflags",
    "//BnesBrowser/components/brave_search_conversion",
    "//BnesBrowser/components/brave_vpn/common/buildflags",
    "//BnesBrowser/components/brave_wallet/common/buildflags",
    "//BnesBrowser/components/constants",
    "//BnesBrowser/components/p3a",
    "//BnesBrowser/components/resources:static_resources",
    "//BnesBrowser/components/resources:strings",
    "//chrome/browser:browser_process",
    "//chrome/browser/metrics",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/search/background",
    "//chrome/browser/ui/webui:webui_util",
    "//chrome/browser/ui/webui/cr_components/theme_color_picker:impl",
    "//chrome/browser/ui/webui/settings",
    "//components/country_codes",
    "//components/regional_capabilities",
    "//content/public/browser",
    "//mojo/public/cpp/bindings",
    "//ui/base",
    "//ui/webui",
  ]

  if (enable_ai_chat) {
    deps += [
      "//BnesBrowser/browser/ai_chat",
      "//BnesBrowser/components/ai_chat/core/common",
    ]
  }

  if (enable_brave_education) {
    deps += [ "//BnesBrowser/browser/ui/webui/brave_education" ]
  }

  if (enable_brave_rewards) {
    deps += [ "//BnesBrowser/browser/brave_rewards:util" ]
  }

  if (enable_brave_vpn) {
    deps += [
      "//BnesBrowser/browser/brave_vpn",
      "//BnesBrowser/components/brave_vpn/common",
    ]
  }

  if (enable_brave_wallet) {
    deps += [
      "//BnesBrowser/browser/brave_wallet",
      "//BnesBrowser/components/brave_wallet/browser",
    ]
  }
}
