# Copyright (c) 2024 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//BnesBrowser/components/ai_chat/core/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/brave_ads/buildflags/buildflags.gni")
import("//BnesBrowser/components/brave_education/buildflags.gni")
import("//BnesBrowser/components/brave_news/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/brave_wallet/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/containers/buildflags/buildflags.gni")
import("//BnesBrowser/components/email_aliases/buildflags/buildflags.gni")
import("//BnesBrowser/components/speedreader/common/buildflags/buildflags.gni")
import("//build/config/ui.gni")

brave_ui_allow_circular_includes_from = []

if (enable_ai_chat) {
  brave_ui_allow_circular_includes_from +=
      [ "//BnesBrowser/browser/ui/webui/ai_chat" ]
}

# TODO(bbondy): Remove this circular dependency when
# chrome/browser/ui/chrome_pages.h gets componentized.
brave_ui_allow_circular_includes_from += [ "//BnesBrowser/browser/ui/brave_origin" ]
if (!is_android) {
  brave_ui_allow_circular_includes_from += [
    "//BnesBrowser/browser/ui/browser_window/internal",
    "//BnesBrowser/browser/ui/tabs:tabs_public",
    "//BnesBrowser/browser/ui/webui/brave_new_tab_page_refresh",
    "//BnesBrowser/browser/ui/webui/brave_welcome_page",
    "//BnesBrowser/browser/ui/webui/side_panel/customize_chrome",
    "//BnesBrowser/browser/ui/tabs:tab_strip",
  ]
  if (enable_brave_education) {
    brave_ui_allow_circular_includes_from +=
        [ "//BnesBrowser/browser/ui/webui/brave_education" ]
  }
  if (enable_brave_news) {
    brave_ui_allow_circular_includes_from += [
      "//BnesBrowser/browser/ui/webui/brave_news",
      "//BnesBrowser/browser/ui/webui/brave_news_internals",
    ]
  }
}
if (is_android) {
  brave_ui_allow_circular_includes_from +=
      [ "//BnesBrowser/browser/ui/webui/new_tab_takeover/android:new_tab_takeover" ]
}
if (toolkit_views) {
  brave_ui_allow_circular_includes_from += [
    "//BnesBrowser/browser/ui/tabs:tab_menu",
    "//BnesBrowser/browser/ui/sidebar:sidebar_impl",
    "//BnesBrowser/browser/ui/split_view",
    "//BnesBrowser/browser/ui/views:layout_provider",
    "//BnesBrowser/browser/ui/views/frame",
    "//BnesBrowser/browser/ui/views/frame:frame_impl",
    "//BnesBrowser/browser/ui/views/frame/split_view",
    "//BnesBrowser/browser/ui/views/frame/vertical_tabs",
    "//BnesBrowser/browser/ui/views/location_bar",
    "//BnesBrowser/browser/ui/views/page_info",
    "//BnesBrowser/browser/ui/views/side_panel:side_panel_impl",
    "//BnesBrowser/browser/ui/views/workspaces",
  ]

  if (enable_ai_chat) {
    brave_ui_allow_circular_includes_from +=
        [ "//BnesBrowser/browser/ui/views/side_panel/ai_chat" ]
  }

  if (enable_containers) {
    brave_ui_allow_circular_includes_from += [ "//BnesBrowser/browser/ui/containers" ]
  }

  if (enable_speedreader) {
    brave_ui_allow_circular_includes_from +=
        [ "//BnesBrowser/browser/ui/views/speedreader" ]
  }
}

if (enable_brave_ads) {
  brave_ui_allow_circular_includes_from +=
      [ "//BnesBrowser/browser/ui/webui/ads_internals" ]
}

if (enable_speedreader) {
  brave_ui_allow_circular_includes_from += [ "//BnesBrowser/browser/ui/speedreader" ]
}

if (enable_email_aliases) {
  brave_ui_allow_circular_includes_from += [
    "//BnesBrowser/browser/ui/email_aliases",
    "//BnesBrowser/browser/ui/webui/email_aliases",
  ]
}

if (enable_brave_wallet) {
  # Need this for these headers:
  # "chrome/browser/ui/webui/favicon_source.h"
  # "chrome/browser/ui/webui/plural_string_handler.h"
  # "chrome/browser/ui/webui/theme_source.h"
  # "brave/browser/ui/webui/brave_rewards/rewards_page_handler.h"
  brave_ui_allow_circular_includes_from += [
    "//BnesBrowser/browser/ui/webui/brave_wallet/wallet_page",
    "//BnesBrowser/browser/ui/webui/brave_wallet/line_chart",
    "//BnesBrowser/browser/ui/webui/brave_wallet/market",
    "//BnesBrowser/browser/ui/webui/brave_wallet/nft",
  ]
  if (!is_android) {
    brave_ui_allow_circular_includes_from +=
        [ "//BnesBrowser/browser/ui/webui/brave_wallet/wallet_panel" ]
  }
}
