# Copyright (c) 2022 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/. */

import("//BnesBrowser/browser/brave_stats/buildflags.gni")
import("//BnesBrowser/components/brave_wallet/common/buildflags/buildflags.gni")
import("//build/buildflag_header.gni")

buildflag_header("buildflags") {
  header = "buildflags.h"
  flags = [
    "BRAVE_USAGE_SERVER=\"$brave_stats_updater_url\"",
    "ENABLE_BRAVE_STATS_UPDATER=$enable_brave_stats_updater",
  ]
}

source_set("first_run_util") {
  sources = [
    "//BnesBrowser/browser/brave_stats/first_run_util.cc",
    "//BnesBrowser/browser/brave_stats/first_run_util.h",
  ]

  deps = [
    "//base",
    "//BnesBrowser/components/constants",
    "//chrome/browser/first_run",
    "//components/prefs",
  ]
}

source_set("brave_stats") {
  sources = [
    "//BnesBrowser/browser/brave_stats/brave_stats_updater_params.cc",
    "//BnesBrowser/browser/brave_stats/brave_stats_updater_params.h",
    "//BnesBrowser/browser/brave_stats/features.cc",
    "//BnesBrowser/browser/brave_stats/features.h",
    "//BnesBrowser/browser/brave_stats/switches.h",
  ]

  if (enable_brave_stats_updater) {
    sources += [
      "//BnesBrowser/browser/brave_stats/brave_stats_updater.cc",
      "//BnesBrowser/browser/brave_stats/brave_stats_updater.h",
    ]
  }

  public_deps = [
    "//BnesBrowser/browser/brave_stats:buildflags",
    "//BnesBrowser/browser/brave_stats:first_run_util",
    "//BnesBrowser/components/brave_stats/browser",
  ]

  deps = [
    "//base",
    "//BnesBrowser/browser:browser_process",
    "//BnesBrowser/browser/misc_metrics",
    "//BnesBrowser/browser/serp_metrics",
    "//BnesBrowser/common",
    "//BnesBrowser/components/brave_origin",
    "//BnesBrowser/components/brave_policy:brave_policy_observer",
    "//BnesBrowser/components/brave_referrals/common",
    "//BnesBrowser/components/brave_wallet/common/buildflags",
    "//BnesBrowser/components/constants",
    "//BnesBrowser/components/misc_metrics",
    "//BnesBrowser/components/serp_metrics",
    "//BnesBrowser/components/serp_metrics:features",
    "//BnesBrowser/components/serp_metrics:prefs",
    "//BnesBrowser/components/version_info",
    "//chrome/browser:browser_process",
    "//chrome/browser/first_run",
    "//chrome/browser/headless",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/profiles:profile_manager",
    "//chrome/browser/profiles:profile_util",
    "//chrome/browser/ui",
    "//chrome/common",
    "//components/prefs",
    "//net",
    "//services/network/public/cpp",
  ]

  if (enable_brave_wallet) {
    deps += [
      "//BnesBrowser/components/brave_wallet/browser",
      "//BnesBrowser/components/brave_wallet/browser:pref_names",
    ]
  }
}

source_set("browser_tests") {
  testonly = true

  sources = []

  if (enable_brave_stats_updater) {
    sources +=
        [ "//BnesBrowser/browser/brave_stats/brave_stats_updater_browsertest.cc" ]
  }

  deps = [
    "//BnesBrowser/browser/brave_stats",
    "//BnesBrowser/components/brave_referrals/browser",
    "//chrome/browser",
    "//chrome/test:test_support",
  ]

  defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]
}

source_set("unit_tests") {
  testonly = true

  sources = [
    "//BnesBrowser/browser/brave_stats/brave_stats_updater_util_unittest.cc",
    "//BnesBrowser/browser/brave_stats/first_run_util_unittest.cc",
  ]

  if (enable_brave_stats_updater) {
    sources += [ "//BnesBrowser/browser/brave_stats/brave_stats_updater_unittest.cc" ]
  }

  deps = [
    "//BnesBrowser/browser/brave_stats",
    "//BnesBrowser/browser/serp_metrics",
    "//BnesBrowser/browser/serp_metrics:test_support",
    "//BnesBrowser/components/brave_referrals/browser",
    "//BnesBrowser/components/brave_stats/browser",
    "//BnesBrowser/components/brave_wallet/common/buildflags",
    "//BnesBrowser/components/misc_metrics",
    "//BnesBrowser/components/serp_metrics:prefs",
    "//chrome/browser",
    "//chrome/browser/prefs",
    "//chrome/browser/profiles:profile_util",
    "//chrome/test:test_support",
    "//components/prefs",
  ]

  if (enable_brave_wallet) {
    deps += [
      "//BnesBrowser/components/brave_wallet/browser",
      "//BnesBrowser/components/brave_wallet/browser:pref_names",
    ]
  }
}
