# Copyright (c) 2023 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//BnesBrowser/components/brave_wallet/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/containers/buildflags/buildflags.gni")
import("//third_party/widevine/cdm/widevine.gni")

brave_components_permissions_sources = [
  "//BnesBrowser/components/permissions/contexts/brave_google_sign_in_permission_context.cc",
  "//BnesBrowser/components/permissions/contexts/brave_google_sign_in_permission_context.h",
  "//BnesBrowser/components/permissions/contexts/brave_open_ai_chat_permission_context.cc",
  "//BnesBrowser/components/permissions/contexts/brave_open_ai_chat_permission_context.h",
  "//BnesBrowser/components/permissions/permission_expiration_key.cc",
  "//BnesBrowser/components/permissions/permission_expiration_key.h",
  "//BnesBrowser/components/permissions/permission_expirations.cc",
  "//BnesBrowser/components/permissions/permission_expirations.h",
  "//BnesBrowser/components/permissions/permission_lifetime_manager.cc",
  "//BnesBrowser/components/permissions/permission_lifetime_manager.h",
  "//BnesBrowser/components/permissions/permission_lifetime_options.cc",
  "//BnesBrowser/components/permissions/permission_lifetime_options.h",
  "//BnesBrowser/components/permissions/permission_lifetime_pref_names.h",
  "//BnesBrowser/components/permissions/permission_lifetime_utils.cc",
  "//BnesBrowser/components/permissions/permission_lifetime_utils.h",
  "//BnesBrowser/components/permissions/permission_origin_lifetime_monitor.h",
  "//BnesBrowser/components/permissions/permission_origins.cc",
  "//BnesBrowser/components/permissions/permission_origins.h",
]

if (enable_widevine) {
  brave_components_permissions_sources += [
    "//BnesBrowser/components/permissions/permission_widevine_utils.cc",
    "//BnesBrowser/components/permissions/permission_widevine_utils.h",
  ]
}

if (enable_brave_wallet) {
  brave_components_permissions_sources += [
    "//BnesBrowser/components/permissions/contexts/brave_wallet_permission_context.cc",
    "//BnesBrowser/components/permissions/contexts/brave_wallet_permission_context.h",
  ]
}

brave_components_permissions_deps = [
  "//base",
  "//BnesBrowser/brave_domains",
  "//BnesBrowser/components/brave_wallet/common/buildflags",
  "//BnesBrowser/components/constants",
  "//BnesBrowser/components/containers/buildflags",
  "//BnesBrowser/components/resources:strings_grit",
  "//components/content_settings/core/browser",
  "//components/content_settings/core/common",
  "//components/keyed_service/core",
  "//components/pref_registry",
  "//services/network/public/mojom",
  "//services/preferences/public/cpp",
  "//third_party/blink/public/common",
  "//ui/base",
  "//url",
]

if (enable_brave_wallet) {
  brave_components_permissions_deps += [
    "//BnesBrowser/components/brave_wallet/browser:permission_utils",
    "//BnesBrowser/components/brave_wallet/common:mojom",
  ]
}

if (enable_containers) {
  brave_components_permissions_deps += [
    "//BnesBrowser/components/containers/content/browser",
    "//BnesBrowser/components/containers/core/common",
  ]
}

if (is_android) {
  brave_components_permissions_deps +=
      [ "//BnesBrowser/components/permissions/android:jni_headers" ]
}
