# Copyright (c) 2025 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//BnesBrowser/components/brave_talk/buildflags/buildflags.gni")
import("//BnesBrowser/components/playlist/core/common/buildflags/buildflags.gni")

config("config") {
  # For our own public headers to be able to import the official public headers
  include_dirs = [
    "//ios/web_view/public",
    "//BnesBrowser/ios/web_view/public",
  ]
}

source_set("web_view") {
  sources = [
    "brave_web_frame.h",
    "brave_web_frame.mm",
    "brave_web_frame_internal.h",
    "brave_web_view.h",
    "brave_web_view.mm",
    "brave_web_view_configuration.h",
    "brave_web_view_configuration.mm",
    "brave_web_view_configuration_provider.h",
    "brave_web_view_configuration_provider.mm",
    "brave_web_view_download_manager.h",
    "brave_web_view_download_manager.mm",
    "brave_web_view_internal.h",
  ]
  deps = [
    "//base",
    "//BnesBrowser/components/ai_chat/core/common",
    "//BnesBrowser/components/ai_chat/ios/browser",
    "//BnesBrowser/components/brave_talk/buildflags",
    "//BnesBrowser/components/playlist/core/common/buildflags",
    "//BnesBrowser/components/serp_metrics:features",
    "//BnesBrowser/ios/browser/ai_chat",
    "//BnesBrowser/ios/browser/api/profile",
    "//BnesBrowser/ios/browser/api/url",
    "//BnesBrowser/ios/browser/api/web_view/autofill",
    "//BnesBrowser/ios/browser/api/web_view/passwords",
    "//BnesBrowser/ios/browser/brave_ads",
    "//BnesBrowser/ios/browser/brave_search",
    "//BnesBrowser/ios/browser/brave_shields",
    "//BnesBrowser/ios/browser/brave_shields/cosmetic_filtering",
    "//BnesBrowser/ios/browser/brave_shields/request_blocking",
    "//BnesBrowser/ios/browser/brave_wallet",
    "//BnesBrowser/ios/browser/favicon",
    "//BnesBrowser/ios/browser/serp_metrics",
    "//BnesBrowser/ios/browser/skus",
    "//BnesBrowser/ios/browser/ui/web_view:features",
    "//BnesBrowser/ios/browser/ui/webui/brave_wallet",
    "//BnesBrowser/ios/browser/web/document_fetch",
    "//BnesBrowser/ios/browser/web/force_paste",
    "//BnesBrowser/ios/browser/web/logins",
    "//BnesBrowser/ios/browser/web/page_metadata",
    "//BnesBrowser/ios/browser/web/reader_mode",
    "//BnesBrowser/ios/browser/youtube",
    "//BnesBrowser/ios/web_view",
    "//components/favicon/core",
    "//ios/chrome/browser/affiliations/model",
    "//ios/chrome/browser/autofill/model",
    "//ios/chrome/browser/favicon/model",
    "//ios/chrome/browser/language/model",
    "//ios/chrome/browser/passwords/model",
    "//ios/chrome/browser/shared/model/profile",
    "//ios/chrome/browser/signin/model",
    "//ios/chrome/browser/sync/model",
    "//ios/chrome/browser/tabs/model",
    "//ios/chrome/browser/translate/model",
    "//ios/chrome/browser/web/model/print",
    "//ios/web/common",
    "//ios/web/web_state",
    "//ios/web/web_state/ui:wk_web_view_configuration_provider_header",
    "//ios/web_view/framework:web_view_sources",
    "//net",
  ]
  if (enable_brave_talk) {
    deps += [ "//BnesBrowser/ios/browser/brave_talk" ]
  }
  if (enable_playlist) {
    deps += [ "//BnesBrowser/ios/browser/playlist" ]
  }
  frameworks = [
    "Foundation.framework",
    "UIKit.framework",
    "WebKit.framework",
  ]
  public_configs = [ ":config" ]
}
