# Copyright (c) 2025 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//BnesBrowser/components/ai_chat/core/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/brave_news/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/brave_rewards/core/buildflags/buildflags.gni")
import("//BnesBrowser/components/brave_vpn/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/brave_wallet/common/buildflags/buildflags.gni")

source_set("customize_chrome") {
  sources = [
    "customize_toolbar/brave_action.h",
    "customize_toolbar/list_action_modifiers.cc",
    "customize_toolbar/list_action_modifiers.h",
  ]

  deps = [
    "//base",
    "//BnesBrowser/app/vector_icons",
    "//BnesBrowser/browser/ui:brave_tab_prefs",
    "//BnesBrowser/browser/ui/screenshot",
    "//BnesBrowser/components/ai_chat/core/common/buildflags",
    "//BnesBrowser/components/brave_news/common/buildflags",
    "//BnesBrowser/components/brave_rewards/core",
    "//BnesBrowser/components/brave_rewards/core/buildflags",
    "//BnesBrowser/components/brave_vpn/common/buildflags",
    "//BnesBrowser/components/brave_wallet/common/buildflags",
    "//BnesBrowser/components/constants",
    "//BnesBrowser/components/resources:strings_grit",
    "//BnesBrowser/components/vector_icons",
    "//chrome/app/vector_icons",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/sharing_hub",
    "//chrome/browser/ui/webui/side_panel/customize_chrome:mojo_bindings",
    "//chrome/browser/ui/webui/util",
    "//chrome/common:constants",
    "//components/omnibox/browser:vector_icons",
    "//components/prefs",
    "//components/user_prefs",
    "//content/public/browser",
  ]

  if (enable_brave_rewards) {
    deps += [ "//BnesBrowser/browser/brave_rewards:util" ]
  }

  if (enable_brave_news) {
    deps += [ "//BnesBrowser/components/brave_news/common" ]
  }

  if (enable_brave_wallet) {
    deps += [
      "//BnesBrowser/browser/brave_wallet",
      "//BnesBrowser/components/brave_wallet/browser:pref_names",
    ]
  }

  if (enable_ai_chat) {
    deps += [
      "//BnesBrowser/components/ai_chat/core/browser",
      "//BnesBrowser/components/ai_chat/core/common",
    ]
  }

  if (enable_brave_vpn_panel) {
    deps += [
      "//BnesBrowser/browser/brave_vpn",
      "//BnesBrowser/components/brave_vpn/common",
    ]
  }
}

source_set("browser_tests") {
  testonly = true
  defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]

  sources = [ "customize_chrome_browsertest.cc" ]

  deps = [
    "//chrome/browser/ui:browser_actions",
    "//chrome/browser/ui/browser_window",
    "//chrome/browser/ui/side_panel:side_panel_views_dependent",
    "//chrome/test:test_support",
    "//chrome/test:test_support_ui",
  ]
}

source_set("unit_tests") {
  testonly = true

  sources = [
    "customize_toolbar/customize_toolbar_handler_unittest.cc",
    "customize_toolbar/list_action_modifiers_unittest.cc",
  ]

  deps = [
    ":customize_chrome",
    "//base",
    "//BnesBrowser/app/vector_icons",
    "//BnesBrowser/browser/ui:brave_tab_prefs",
    "//BnesBrowser/browser/ui/screenshot",
    "//BnesBrowser/components/ai_chat/core/common/buildflags",
    "//BnesBrowser/components/brave_news/common/buildflags",
    "//BnesBrowser/components/brave_rewards/core",
    "//BnesBrowser/components/brave_rewards/core/buildflags",
    "//BnesBrowser/components/brave_vpn/common/buildflags",
    "//BnesBrowser/components/brave_wallet/common/buildflags",
    "//BnesBrowser/components/l10n/common:test_support",
    "//BnesBrowser/components/resources:strings_grit",
    "//BnesBrowser/components/vector_icons",
    "//chrome/browser/sharing_hub",
    "//chrome/browser/ui/webui/util",
    "//chrome/test:test_support",
    "//components/prefs",
    "//components/sync_preferences:test_support",
    "//components/user_prefs",
    "//content/public/browser",
    "//content/test:test_support",
    "//testing/gmock",
    "//testing/gtest",
    "//ui/base",
  ]

  if (enable_brave_rewards) {
    deps += [ "//BnesBrowser/browser/brave_rewards:util" ]
  }

  if (enable_brave_news) {
    deps += [ "//BnesBrowser/components/brave_news/common" ]
  }

  if (enable_brave_wallet) {
    deps += [
      "//BnesBrowser/browser/brave_wallet",
      "//BnesBrowser/components/brave_wallet/browser:pref_names",
    ]
  }

  if (enable_ai_chat) {
    deps += [
      "//BnesBrowser/components/ai_chat/core/browser",
      "//BnesBrowser/components/ai_chat/core/common",
    ]
  }

  if (enable_brave_vpn_panel) {
    deps += [
      "//BnesBrowser/browser/brave_vpn",
      "//BnesBrowser/components/brave_vpn/common",
    ]
  }
}
