# Copyright (c) 2023 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//BnesBrowser/components/ai_chat/core/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/brave_wallet/common/buildflags/buildflags.gni")
import("//extensions/buildflags/buildflags.gni")

source_set("misc_metrics") {
  sources = [
    "//BnesBrowser/browser/misc_metrics/media_session_metrics_impl.h",
    "//BnesBrowser/browser/misc_metrics/process_misc_metrics.h",
    "//BnesBrowser/browser/misc_metrics/profile_misc_metrics_service.h",
    "//BnesBrowser/browser/misc_metrics/profile_misc_metrics_service_factory.h",
  ]

  deps = [
    "//BnesBrowser/components/ai_chat/core/common/buildflags",
    "//BnesBrowser/components/misc_metrics",
    "//BnesBrowser/components/time_period_storage",
    "//components/keyed_service/content",
    "//components/keyed_service/core",
    "//components/prefs",
    "//content/public/browser",
    "//mojo/public/cpp/bindings",
    "//services/media_session/public/mojom",
  ]
}

static_library("misc_metrics_impl") {
  visibility = [
    "//BnesBrowser/browser:core",
    "//BnesBrowser/browser/misc_metrics/*",
  ]

  sources = [
    "//BnesBrowser/browser/misc_metrics/doh_metrics.cc",
    "//BnesBrowser/browser/misc_metrics/doh_metrics.h",
    "//BnesBrowser/browser/misc_metrics/fingerprint_frequency_metrics.cc",
    "//BnesBrowser/browser/misc_metrics/fingerprint_frequency_metrics.h",
    "//BnesBrowser/browser/misc_metrics/media_session_metrics_impl.cc",
    "//BnesBrowser/browser/misc_metrics/page_metrics_tab_helper.cc",
    "//BnesBrowser/browser/misc_metrics/page_metrics_tab_helper.h",
    "//BnesBrowser/browser/misc_metrics/process_misc_metrics.cc",
    "//BnesBrowser/browser/misc_metrics/uptime_monitor_impl.h",
  ]

  deps = [
    "//base",
    "//BnesBrowser/browser:browser_process",
    "//BnesBrowser/browser/brave_search",
    "//BnesBrowser/browser/brave_stats",
    "//BnesBrowser/browser/misc_metrics",
    "//BnesBrowser/browser/profiles:util",
    "//BnesBrowser/components/brave_shields/core/common",
    "//BnesBrowser/components/constants",
    "//BnesBrowser/components/misc_metrics",
    "//BnesBrowser/components/p3a_utils",
    "//BnesBrowser/components/resources:static_resources_grit",
    "//BnesBrowser/components/script_injector/common/mojom",
    "//BnesBrowser/components/time_period_storage",
    "//chrome/browser:browser_process",
    "//chrome/browser:shell_integration",
    "//chrome/browser/autofill",
    "//chrome/browser/profiles",
    "//chrome/browser/search_engines",
    "//chrome/browser/ui",
    "//chrome/browser/ui/browser_window",
    "//chrome/common:constants",
    "//components/keyed_service/content",
    "//components/keyed_service/core",
    "//components/language/core/browser",
    "//components/prefs",
    "//components/tabs:public",
    "//components/user_prefs",
    "//content/public/browser",
    "//content/public/common",
    "//mojo/public/cpp/bindings",
    "//services/media_session/public/mojom",
    "//third_party/blink/public/common",
    "//ui/base",
    "//ui/gfx/geometry",
  ]

  if (enable_ai_chat) {
    deps += [ "//BnesBrowser/components/ai_chat/core/browser" ]
  }

  if (enable_extensions) {
    sources += [
      "//BnesBrowser/browser/misc_metrics/extension_metrics.cc",
      "//BnesBrowser/browser/misc_metrics/extension_metrics.h",
    ]

    deps += [ "//BnesBrowser/browser/extensions/manifest_v2" ]
  }

  if (!is_android) {
    sources += [
      "//BnesBrowser/browser/misc_metrics/default_browser_monitor_delegate_impl.cc",
      "//BnesBrowser/browser/misc_metrics/default_browser_monitor_delegate_impl.h",
      "//BnesBrowser/browser/misc_metrics/theme_metrics.cc",
      "//BnesBrowser/browser/misc_metrics/theme_metrics.h",
      "//BnesBrowser/browser/misc_metrics/vertical_tab_metrics.cc",
      "//BnesBrowser/browser/misc_metrics/vertical_tab_metrics.h",
    ]
    deps += [
      "//BnesBrowser/browser/extensions/manifest_v2",
      "//BnesBrowser/browser/themes",
      "//chrome/browser/themes",
      "//chrome/browser/ui/tabs:tab_strip",
      "//extensions/browser",
    ]
  } else {
    sources += [ "//BnesBrowser/browser/misc_metrics/misc_android_metrics.h" ]
    deps += [
      "//chrome/browser/flags:flags_android",
      "//chrome/browser/ui/android/tab_model",
    ]
  }
}

if (!is_android) {
  source_set("usage_clock") {
    sources = [
      "//BnesBrowser/browser/misc_metrics/usage_clock.cc",
      "//BnesBrowser/browser/misc_metrics/usage_clock.h",
    ]

    deps = [
      "//base",
      "//chrome/browser/metrics/desktop_session_duration",
    ]
  }
}

source_set("unit_tests") {
  testonly = true

  sources = [
    "doh_metrics_unittest.cc",
    "fingerprint_frequency_metrics_unittest.cc",
    "media_session_metrics_impl_unittest.cc",
    "page_metrics_unittest.cc",
    "uptime_monitor_impl_unittest.cc",
  ]

  deps = [
    "//base",
    "//base/test:test_support",
    "//BnesBrowser/browser",
    "//BnesBrowser/browser/misc_metrics",
    "//BnesBrowser/browser/misc_metrics:misc_metrics_impl",
    "//BnesBrowser/components/brave_rewards/core",
    "//BnesBrowser/components/misc_metrics",
    "//BnesBrowser/components/p3a_utils:test_support",
    "//chrome/browser",
    "//chrome/browser/bookmarks",
    "//chrome/browser/content_settings:content_settings_factory",
    "//chrome/browser/history",
    "//chrome/browser/search_engines",
    "//chrome/common",
    "//chrome/test:test_support",
    "//components/bookmarks/browser",
    "//components/prefs:test_support",
    "//components/search_engines",
    "//content/test:test_support",
    "//mojo/public/cpp/bindings",
    "//services/media_session/public/mojom",
    "//testing/gtest",
  ]

  if (!is_android) {
    sources += [
      "profile_new_tab_metrics_unittest.cc",
      "theme_metrics_unittest.cc",
      "usage_clock_unittest.cc",
    ]

    deps += [
      ":usage_clock",
      "//BnesBrowser/browser/themes",
      "//chrome/browser/metrics/desktop_session_duration",
      "//chrome/browser/themes",
    ]
  }

  if (enable_extensions) {
    sources += [ "extension_metrics_unittest.cc" ]

    deps += [ "//BnesBrowser/browser/extensions/manifest_v2" ]
  }
}

source_set("browser_tests") {
  testonly = true

  sources = [ "fingerprint_frequency_metrics_browsertest.cc" ]

  # The web3 proxy is only injected alongside a wallet provider.
  if (enable_brave_wallet) {
    sources += [ "web3_metrics_browsertest.cc" ]
  }

  if (!is_android) {
    sources += [ "vertical_tab_metrics_browsertest.cc" ]
  }

  deps = [
    "//base",
    "//base/test:test_support",
    "//BnesBrowser/browser/misc_metrics:misc_metrics_impl",
    "//BnesBrowser/components/constants",
    "//BnesBrowser/components/misc_metrics",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/tab_group_sync:factories",
    "//chrome/test:test_support",
    "//components/language/core/browser",
    "//components/prefs:test_support",
    "//content/test:test_support",
    "//net:test_support",
    "//testing/gtest",
    "//url",
  ]

  if (enable_brave_wallet) {
    deps += [
      "//BnesBrowser/browser/brave_wallet",
      "//BnesBrowser/components/brave_wallet/browser",
      "//BnesBrowser/components/brave_wallet/browser:test_support",
    ]
  }

  defines = [ "HAS_OUT_OF_PROC_TEST_RUNNER" ]
}
