# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//BnesBrowser/components/containers/buildflags/buildflags.gni")

source_set("enterprise") {
  sources = [ "platform_auth_helper.cc" ]

  deps = [
    "//BnesBrowser/components/containers/buildflags",
    "//content/public/browser",
  ]

  if (enable_containers) {
    deps += [
      "//BnesBrowser/components/containers/content/browser",
      "//BnesBrowser/components/containers/core/common",
    ]
  }
}
