# Copyright (c) 2021 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//BnesBrowser/components/brave_rewards/core/buildflags/buildflags.gni")
import("//BnesBrowser/components/tor/buildflags/buildflags.gni")

brave_utility_importer_sources = []
brave_utility_importer_deps = []
brave_utility_importer_public_deps = []

if (!is_android) {
  brave_utility_importer_sources += [
    "//BnesBrowser/utility/importer/brave_external_process_importer_bridge.cc",
    "//BnesBrowser/utility/importer/brave_external_process_importer_bridge.h",
    "//BnesBrowser/utility/importer/brave_profile_import_impl.cc",
    "//BnesBrowser/utility/importer/brave_profile_import_impl.h",
    "//BnesBrowser/utility/importer/chrome_importer.cc",
    "//BnesBrowser/utility/importer/chrome_importer.h",
  ]

  brave_utility_importer_deps += [
    "//base",
    "//BnesBrowser/app:brave_generated_resources_grit",
    "//BnesBrowser/common/importer",
    "//BnesBrowser/common/importer:interfaces",
    "//chrome/app:branded_strings",
    "//components/user_data_importer/common",
  ]
}

if (enable_brave_rewards) {
  brave_utility_importer_public_deps +=
      [ "//BnesBrowser/components/services/bat_rewards:lib" ]
}

if (enable_tor) {
  brave_utility_importer_deps += [ "//BnesBrowser/components/services/tor" ]
}
