# Copyright (c) 2024 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//mojo/public/tools/bindings/mojom.gni")

source_set("zcash_decoder") {
  visibility = [ "//BnesBrowser/components/services/brave_wallet/*" ]

  sources = [
    "zcash_decoder.cc",
    "zcash_decoder.h",
  ]

  deps = [
    "//base",
    "//BnesBrowser/components/brave_wallet/common",
    "//BnesBrowser/components/services/brave_wallet/public/cpp/utils",
    "//BnesBrowser/components/services/brave_wallet/public/mojom",
    "//BnesBrowser/components/services/brave_wallet/public/proto:zcash_proto",
  ]
}

source_set("zcash_decoder_unit_tests") {
  testonly = true
  sources = [ "zcash_decoder_unittest.cc" ]

  deps = [
    "//base/test:test_support",
    "//BnesBrowser/components/brave_wallet/common",
    "//BnesBrowser/components/brave_wallet/common:test_support",
    "//BnesBrowser/components/services/brave_wallet/public/cpp/utils",
    "//BnesBrowser/components/services/brave_wallet/public/proto:zcash_proto",
    "//BnesBrowser/components/services/brave_wallet/zcash:zcash_decoder",
    "//testing/gtest",
  ]
}
