# Copyright (c) 2024 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

brave_flags_deps = [
  "//base",
  "//BnesBrowser/components/ai_chat/core/common",
  "//BnesBrowser/components/brave_ads/core",
  "//BnesBrowser/components/brave_component_updater/browser:public",
  "//BnesBrowser/components/brave_origin:features",
  "//BnesBrowser/components/brave_rewards/core",
  "//BnesBrowser/components/brave_rewards/core/buildflags",
  "//BnesBrowser/components/brave_shields/core/common",
  "//BnesBrowser/components/brave_sync:features",
  "//BnesBrowser/components/brave_user_agent/common",
  "//BnesBrowser/components/brave_wallet/common",
  "//BnesBrowser/components/de_amp/common",
  "//BnesBrowser/components/debounce/core/common",
  "//BnesBrowser/components/playlist/core/common",
  "//BnesBrowser/components/skus/common",
  "//BnesBrowser/ios/browser/brave_wallet",
  "//BnesBrowser/ios/browser/ui/quick_view:features",
  "//BnesBrowser/ios/browser/ui/web_view:features",
  "//components/webui/flags",
  "//net",
]
