# Copyright (c) 2025 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//BnesBrowser/components/brave_talk/buildflags/buildflags.gni")
import("//BnesBrowser/components/brave_vpn/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/brave_wallet/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/email_aliases/buildflags/buildflags.gni")

source_set("prefs") {
  sources = [
    "browser_prefs_impl.mm",
    "pref_names.h",
    "shared_pref_names_bridge.h",
    "shared_pref_names_bridge.mm",
  ]
  deps = [
    "//BnesBrowser/components/ai_chat/core/browser",
    "//BnesBrowser/components/ai_chat/core/common",
    "//BnesBrowser/components/brave_account",
    "//BnesBrowser/components/brave_ads/core",
    "//BnesBrowser/components/brave_news/common",
    "//BnesBrowser/components/brave_origin",
    "//BnesBrowser/components/brave_rewards/core",
    "//BnesBrowser/components/brave_shields/core/browser",
    "//BnesBrowser/components/brave_shields/core/common",
    "//BnesBrowser/components/brave_sync:prefs",
    "//BnesBrowser/components/brave_talk/buildflags",
    "//BnesBrowser/components/brave_vpn/common/buildflags",
    "//BnesBrowser/components/brave_wallet/common/buildflags",
    "//BnesBrowser/components/constants",
    "//BnesBrowser/components/de_amp/common",
    "//BnesBrowser/components/debounce/core/browser",
    "//BnesBrowser/components/email_aliases/buildflags",
    "//BnesBrowser/components/global_privacy_control",
    "//BnesBrowser/components/l10n/common",
    "//BnesBrowser/components/ntp_background_images/browser",
    "//BnesBrowser/components/ntp_background_images/common",
    "//BnesBrowser/components/p3a",
    "//BnesBrowser/components/playlist/core/common",
    "//BnesBrowser/components/skus/browser",
    "//BnesBrowser/ios/browser/brave_stats",
    "//BnesBrowser/ios/browser/youtube",
    "//components/metrics",
    "//components/omnibox/browser",
    "//components/pref_registry",
    "//components/prefs",
    "//ios/chrome/browser/shared/model/prefs",
    "//ios/chrome/common",
  ]
  if (enable_brave_vpn) {
    deps += [ "//BnesBrowser/components/brave_vpn/common" ]
  }
  if (enable_brave_wallet) {
    deps += [
      "//BnesBrowser/components/brave_wallet/browser",
      "//BnesBrowser/components/brave_wallet/browser:pref_names",
      "//BnesBrowser/components/decentralized_dns/core",
    ]
  }
  if (enable_brave_talk) {
    deps += [ "//BnesBrowser/components/brave_talk" ]
  }
  if (enable_email_aliases) {
    deps += [ "//BnesBrowser/components/email_aliases:service" ]
  }
}
