# Copyright (c) 2022 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

brave_components_update_client_sources = [
  "//BnesBrowser/components/update_client/privacy_preserving_protocol_handler.cc",
  "//BnesBrowser/components/update_client/privacy_preserving_protocol_handler.h",
  "//BnesBrowser/components/update_client/privacy_preserving_protocol_serializer.cc",
  "//BnesBrowser/components/update_client/privacy_preserving_protocol_serializer.h",
]

brave_components_update_client_deps = [
  "//BnesBrowser/components/constants",
  "//BnesBrowser/components/widevine:constants",
]

brave_components_update_client_public_deps =
    [ "//BnesBrowser/components/update_client:buildflags" ]
