# Copyright (c) 2022 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//BnesBrowser/build/config.gni")
import("//BnesBrowser/components/brave_ads/buildflags/buildflags.gni")

assert(is_android)

source_set("android_browser_process") {
  sources = [
    "brave_feature_util.cc",
    "brave_local_state_android.cc",
    "brave_relaunch_utils.cc",
    "brave_shields_content_settings.cc",
    "brave_shields_content_settings.h",
    "brave_sync_worker.cc",
    "brave_sync_worker.h",
  ]

  deps = [
    "//base",
    "//BnesBrowser/brave_domains/android:jni_headers",
    "//BnesBrowser/browser/android/browsing_data",
    "//BnesBrowser/browser/android/preferences",
    "//BnesBrowser/browser/android/safe_browsing",
    "//BnesBrowser/browser/brave_origin/android:jni_headers",
    "//BnesBrowser/browser/brave_shields",
    "//BnesBrowser/browser/skus/android:jni_headers",
    "//BnesBrowser/build/android:jni_headers",
    "//BnesBrowser/components/brave_ads/buildflags",
    "//BnesBrowser/components/brave_shields/content/browser",
    "//BnesBrowser/components/brave_shields/core/browser",
    "//BnesBrowser/components/brave_shields/core/common",
    "//BnesBrowser/components/brave_sync",
    "//BnesBrowser/components/brave_sync:crypto",
    "//BnesBrowser/components/brave_sync:prefs",
    "//BnesBrowser/components/brave_sync:sync_service_impl_helper",
    "//BnesBrowser/components/brave_sync:time_limited_codes",
    "//chrome/android:jni_headers",
    "//chrome/browser:browser_process",
    "//chrome/browser:browser_public_dependencies",
    "//chrome/browser:flags",
    "//chrome/browser/content_settings:content_settings_factory",
    "//chrome/browser/lifetime",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/sync",
    "//chrome/common",
    "//components/content_settings/core/browser",
    "//components/content_settings/core/browser:cookie_settings",
    "//components/ntp_tiles",
    "//components/prefs",
    "//components/sync",
    "//components/translate/core/browser",
    "//components/unified_consent",
    "//components/webui/flags",
    "//url",
  ]

  if (enable_brave_ads) {
    deps += [
      "//BnesBrowser/browser/brave_ads/android:jni_headers",
      "//BnesBrowser/components/brave_ads/browser",
    ]
  }
}

source_set("tabs_public") {
  public = [ "brave_tab_features.h" ]

  public_deps = [ "//chrome/browser/android:tabs_public" ]
}

source_set("tabs_impl") {
  visibility = [ "//BnesBrowser/browser:core" ]
  sources = [ "brave_tab_features.cc" ]

  deps = [
    ":tabs_public",
    "//base",
    "//BnesBrowser/browser/ai_chat",
    "//chrome/browser/profiles:profile",
    "//content/public/browser",
  ]
}
