# Copyright (c) 2022 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//BnesBrowser/components/ai_chat/core/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/brave_ads/buildflags/buildflags.gni")
import("//BnesBrowser/components/brave_news/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/brave_talk/buildflags/buildflags.gni")
import("//BnesBrowser/components/brave_vpn/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/brave_wallet/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/brave_wayback_machine/buildflags/buildflags.gni")
import("//BnesBrowser/components/containers/buildflags/buildflags.gni")
import("//BnesBrowser/components/email_aliases/buildflags/buildflags.gni")
import("//BnesBrowser/components/playlist/core/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/psst/buildflags/buildflags.gni")
import("//BnesBrowser/components/speedreader/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/tor/buildflags/buildflags.gni")
import("//BnesBrowser/components/traffic_control/buildflags/buildflags.gni")
import("//BnesBrowser/components/web_discovery/buildflags/buildflags.gni")
import("//build/config/features.gni")
import("//build/config/ui.gni")
import("//components/gcm_driver/config.gni")

assert(toolkit_views)

source_set("component_loader") {
  sources = [
    "brave_component_loader.cc",
    "brave_component_loader.h",
  ]

  deps = [
    "//base",
    "//BnesBrowser/components/brave_extension:static_resources",
    "//chrome/browser/extensions",
    "//chrome/browser/profiles:profile",
    "//components/prefs",
    "//extensions/browser",
    "//extensions/common",
    "//ui/base",
  ]

  if (enable_web_discovery_native) {
    deps += [ "//BnesBrowser/components/web_discovery/common" ]
  }
}

# This is split out from extensions and the rest of brave_prefs_util because it
# has circular dependencies on //chrome/browser.
# https://github.com/brave/brave-browser/issues/41418
source_set("brave_prefs_util_impl") {
  visibility = [
    ":*",
    "//BnesBrowser/browser:core",
  ]
  sources = [ "api/settings_private/brave_prefs_util_impl.cc" ]

  deps = [
    "//BnesBrowser/components/brave_shields/core/browser",
    "//chrome/browser:browser_public_dependencies",
    "//chrome/browser/content_settings:content_settings_factory",
    "//chrome/browser/profiles:profile",
    "//chrome/common/extensions/api",
    "//components/content_settings/core/browser:cookie_settings",
    "//components/content_settings/core/common",
    "//content/public/browser",
    "//url",
  ]
}

source_set("extensions") {
  sources = [
    "api/brave_extensions_api_client.cc",
    "api/brave_extensions_api_client.h",
    "api/brave_theme_api.cc",
    "api/brave_theme_api.h",
    "api/identity/brave_web_auth_flow.cc",
    "api/identity/brave_web_auth_flow.h",
    "api/settings_private/brave_prefs_util.cc",
    "api/settings_private/brave_prefs_util.h",
    "brave_extension_management.cc",
    "brave_extension_management.h",
    "brave_extension_provider.cc",
    "brave_extension_provider.h",
    "brave_extensions_browser_api_provider.cc",
    "brave_extensions_browser_api_provider.h",
    "brave_extensions_browser_client_impl.cc",
    "brave_extensions_browser_client_impl.h",
    "updater/brave_update_client_config.cc",
    "updater/brave_update_client_config.h",
    "updater/features.cc",
    "updater/features.h",
  ]

  deps = [
    ":brave_prefs_util_impl",
    ":resources",
    "//BnesBrowser/app:brave_generated_resources_grit",
    "//BnesBrowser/browser:browser_process",
    "//BnesBrowser/browser/brave_search",
    "//BnesBrowser/browser/component_updater",
    "//BnesBrowser/browser/extensions/api:generated_api_registration",
    "//BnesBrowser/browser/ui:brave_tab_prefs",
    "//BnesBrowser/common",
    "//BnesBrowser/common/extensions/api",
    "//BnesBrowser/components/ai_chat/core/common/buildflags",
    "//BnesBrowser/components/brave_ads/buildflags",
    "//BnesBrowser/components/brave_extension:static_resources",
    "//BnesBrowser/components/brave_news/common/buildflags",
    "//BnesBrowser/components/brave_rewards/core",
    "//BnesBrowser/components/brave_search/browser",
    "//BnesBrowser/components/brave_shields/core/common",
    "//BnesBrowser/components/brave_talk/buildflags",
    "//BnesBrowser/components/brave_vpn/common/buildflags",
    "//BnesBrowser/components/brave_wallet/common/buildflags",
    "//BnesBrowser/components/brave_wayback_machine/buildflags",
    "//BnesBrowser/components/constants",
    "//BnesBrowser/components/containers/buildflags",
    "//BnesBrowser/components/de_amp/common",
    "//BnesBrowser/components/debounce/core/common",
    "//BnesBrowser/components/email_aliases/buildflags",
    "//BnesBrowser/components/ntp_background_images/common",
    "//BnesBrowser/components/request_otr/common",
    "//BnesBrowser/components/sidebar/browser",
    "//BnesBrowser/components/speedreader/common/buildflags",
    "//BnesBrowser/components/tor/buildflags",
    "//BnesBrowser/components/traffic_control/buildflags",
    "//BnesBrowser/components/web_discovery/buildflags",
    "//BnesBrowser/components/webcompat_reporter/common",
    "//chrome/browser:browser_process",
    "//chrome/browser:browser_public_dependencies",
    "//chrome/browser/extensions",
    "//chrome/browser/extensions:chrome_extensions_browser_client",
    "//chrome/browser/profiles:profile",
    "//chrome/browser/ui",
    "//chrome/browser/ui/browser_window",
    "//chrome/common",
    "//components/browsing_data/core",
    "//components/gcm_driver:gcm_buildflags",
    "//components/history/core/common",
    "//components/prefs",
    "//components/update_client:network_impl",
    "//components/user_prefs",
    "//content/public/browser",
  ]

  public_deps = [
    ":component_loader",
    "//base",
    "//extensions/browser",
  ]

  if (use_gcm_from_platform) {
    deps += [ "//components/gcm_driver" ]
  }

  if (enable_brave_ads) {
    deps += [ "//BnesBrowser/components/brave_ads/core/public:headers" ]
  }

  if (enable_brave_wayback_machine) {
    deps += [ "//BnesBrowser/components/brave_wayback_machine" ]
  }

  if (enable_speedreader) {
    deps += [ "//BnesBrowser/components/speedreader" ]
  }

  if (enable_ai_chat) {
    deps += [ "//BnesBrowser/components/ai_chat/core/common" ]
  }

  if (enable_brave_news) {
    deps += [ "//BnesBrowser/components/brave_news/common" ]
  }

  if (enable_brave_vpn) {
    deps += [ "//BnesBrowser/components/brave_vpn/common" ]
  }

  if (enable_tor) {
    deps += [
      "//BnesBrowser/browser/tor",
      "//BnesBrowser/components/tor",
      "//BnesBrowser/components/tor:pref_names",
    ]
  }

  if (enable_web_discovery) {
    sources += [
      "api/web_discovery_api.cc",
      "api/web_discovery_api.h",
    ]
  }

  if (enable_web_discovery_native) {
    deps += [ "//BnesBrowser/components/web_discovery/common" ]
  }

  if (is_win) {
    deps += [ "//BnesBrowser/components/windows_recall" ]
  }

  if (enable_brave_wallet) {
    deps += [
      "//BnesBrowser/components/brave_wallet/browser",
      "//BnesBrowser/components/brave_wallet/browser:pref_names",
      "//BnesBrowser/components/brave_wallet/browser:utils",
      "//BnesBrowser/components/brave_wallet/common",
      "//BnesBrowser/components/decentralized_dns/core",
    ]
  }

  if (enable_brave_talk) {
    sources += [
      "api/brave_talk_api.cc",
      "api/brave_talk_api.h",
    ]
    deps += [ "//BnesBrowser/components/brave_talk" ]
  }

  if (enable_playlist) {
    deps += [ "//BnesBrowser/components/playlist/core/common" ]
  }

  if (enable_psst) {
    deps += [ "//BnesBrowser/components/psst/core/browser" ]
  }

  if (enable_email_aliases) {
    deps += [ "//BnesBrowser/components/email_aliases:pref_names" ]
  }

  if (enable_containers) {
    deps += [ "//BnesBrowser/components/containers/core/browser" ]
  }

  if (enable_traffic_control) {
    deps += [ "//BnesBrowser/components/traffic_control/core/browser" ]
  }

  allow_circular_includes_from = [ ":brave_prefs_util_impl" ]
}

group("resources") {
  deps = [
    "//BnesBrowser/components/brave_extension:generated_resources",
    "//BnesBrowser/components/brave_extension:static_resources",
  ]
}

source_set("test_support") {
  testonly = true

  sources = [
    "brave_base_local_data_files_browsertest.cc",
    "brave_base_local_data_files_browsertest.h",
    "brave_extension_functional_test.cc",
    "brave_extension_functional_test.h",
  ]

  deps = [
    "//base",
    "//base/test:test_support",
    "//BnesBrowser/browser",
    "//BnesBrowser/components/brave_component_updater/browser",
    "//BnesBrowser/components/constants",
    "//chrome/browser/extensions",
    "//chrome/test:test_support",
    "//content/public/browser",
    "//content/test:test_support",
    "//extensions/browser:crx_installer",
    "//net",
    "//net:test_support",
  ]
}
