# Copyright (c) 2022 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//BnesBrowser/components/brave_vpn/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/brave_wallet/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/speedreader/common/buildflags/buildflags.gni")
import("//build/config/features.gni")

source_set("renderer") {
  visibility = [
    "//BnesBrowser:child_dependencies",
    "//BnesBrowser/renderer/*",
    "//BnesBrowser/test:*",
    "//chrome/renderer/*",
  ]

  public_deps = [ "//chrome/renderer" ]

  deps = [
    "//BnesBrowser/components/brave_search/common",
    "//BnesBrowser/components/brave_search/renderer",
    "//BnesBrowser/components/brave_shields/core/common",
    "//BnesBrowser/components/cosmetic_filters/renderer",
    "//v8",
  ]

  if (enable_brave_wallet) {
    deps += [
      "//BnesBrowser/components/brave_wallet/renderer",
      "//BnesBrowser/renderer/brave_wallet/",
    ]
  }

  if (enable_speedreader) {
    deps += [ "//BnesBrowser/components/speedreader/renderer" ]
  }

  if (is_android) {
    deps += [ "//BnesBrowser/components/brave_mobile_subscription/renderer/android" ]
  }
}
