# Copyright (c) 2023 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//BnesBrowser/components/brave_wallet/common/buildflags/buildflags.gni")

source_set("features") {
  sources = [
    "features.h",
    "features.mm",
  ]

  deps = [
    "//base",
    "//BnesBrowser/components/ai_chat/core/common",
    "//BnesBrowser/components/brave_component_updater/browser:public",
    "//BnesBrowser/components/brave_news/common",
    "//BnesBrowser/components/brave_origin:features",
    "//BnesBrowser/components/brave_rewards/core:features",
    "//BnesBrowser/components/brave_search/common",
    "//BnesBrowser/components/brave_search_conversion",
    "//BnesBrowser/components/brave_shields/core/common",
    "//BnesBrowser/components/brave_sync:features",
    "//BnesBrowser/components/brave_user_agent/common",
    "//BnesBrowser/components/brave_wallet/common/buildflags",
    "//BnesBrowser/components/de_amp/common",
    "//BnesBrowser/components/debounce/core/common",
    "//BnesBrowser/components/ntp_background_images/browser",
    "//BnesBrowser/components/p3a",
    "//BnesBrowser/components/playlist/core/common",
    "//BnesBrowser/components/serp_metrics:features",
    "//BnesBrowser/components/skus/common",
    "//BnesBrowser/ios/browser/api/translate:features",
    "//BnesBrowser/ios/browser/playlist:features",
    "//BnesBrowser/ios/browser/ui/commerce:features",
    "//BnesBrowser/ios/browser/ui/quick_view:features",
    "//BnesBrowser/ios/browser/ui/web_view:features",
    "//build:blink_buildflags",
    "//net",
  ]

  if (enable_brave_wallet) {
    deps += [
      "//BnesBrowser/components/brave_wallet/common",
      "//BnesBrowser/ios/browser/brave_wallet",
    ]
  }

  frameworks = [ "Foundation.framework" ]
}
