# Copyright (c) 2024 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//BnesBrowser/components/brave_ads/buildflags/buildflags.gni")

brave_browser_brave_rewards_android_sources = [
  "//BnesBrowser/browser/brave_rewards/android/brave_rewards_native_worker.cc",
  "//BnesBrowser/browser/brave_rewards/android/brave_rewards_native_worker.h",
]

brave_browser_brave_rewards_android_deps = [
  "//base",
  "//BnesBrowser/components/brave_adaptive_captcha",
  "//BnesBrowser/components/brave_ads/buildflags",
  "//BnesBrowser/components/brave_ads/core/browser/service",
  "//BnesBrowser/components/brave_ads/core/mojom",
  "//BnesBrowser/components/brave_rewards/content",
  "//BnesBrowser/components/brave_rewards/core",
  "//BnesBrowser/components/brave_rewards/core/mojom",
  "//chrome/android:chrome_jni_headers",
  "//chrome/browser/profiles:profile",
  "//components/prefs",
  "//content/public/browser",
  "//third_party/abseil-cpp:absl",
]

if (enable_brave_ads) {
  brave_browser_brave_rewards_android_deps += [
    "//BnesBrowser/browser/brave_ads",
    "//BnesBrowser/components/brave_ads/core/public:headers",
  ]
}
