# Copyright (c) 2023 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

brave_chrome_common_sources = [
  "//BnesBrowser/common/brave_channel_info.cc",
  "//BnesBrowser/common/brave_channel_info.h",
  "//BnesBrowser/common/pref_names.h",
  "//BnesBrowser/common/resource_bundle_helper.cc",
  "//BnesBrowser/common/resource_bundle_helper.h",
]

brave_chrome_common_deps = [
  "//base",
  "//BnesBrowser/common:mojo_bindings",
  "//BnesBrowser/components/brave_origin/buildflags",
  "//components/version_info:channel",
  "//extensions/buildflags",
  "//services/service_manager",
  "//ui/base",
]

brave_chrome_common_public_deps = [
  "//BnesBrowser/app_shim",
  "//BnesBrowser/components/constants",
]

brave_chrome_constants_deps = [ "//BnesBrowser/components/brave_origin/buildflags" ]

if (is_android) {
  brave_chrome_common_deps += [ "//components/user_data_importer/common" ]
}

if (!is_android && !is_ios) {
  brave_chrome_common_deps += [ "//BnesBrowser/common/importer" ]
}

if (!is_ios) {
  brave_chrome_common_sources += [
    "//BnesBrowser/common/brave_content_client.cc",
    "//BnesBrowser/common/brave_content_client.h",
  ]

  brave_chrome_common_deps += [
    "//BnesBrowser/components/resources",
    "//BnesBrowser/components/resources:static_resources_grit",
    "//chrome/common:channel_info",
    "//chrome/common:constants",
    "//components/resources",
    "//content/public/common",
    "//third_party/widevine/cdm:buildflags",
  ]
}
