# Copyright (c) 2020 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

import("//extensions/buildflags/buildflags.gni")

brave_browser_importer_sources = []
brave_browser_importer_public_deps = []
brave_browser_importer_impl_sources = []
brave_browser_importer_impl_deps = []

if (!is_android) {
  brave_browser_importer_sources += [
    "//BnesBrowser/browser/importer/brave_external_process_importer_host.h",
    "//BnesBrowser/browser/importer/brave_password_importer.h",
  ]
  brave_browser_importer_public_deps += [
    "//base",
    "//chrome/common/extensions",
    "//extensions/buildflags",
  ]
  brave_browser_importer_impl_sources += [
    "//BnesBrowser/browser/importer/brave_external_process_importer_client.cc",
    "//BnesBrowser/browser/importer/brave_external_process_importer_client.h",
    "//BnesBrowser/browser/importer/brave_external_process_importer_host.cc",
    "//BnesBrowser/browser/importer/brave_in_process_importer_bridge.cc",
    "//BnesBrowser/browser/importer/brave_in_process_importer_bridge.h",
    "//BnesBrowser/browser/importer/brave_password_importer.cc",
  ]
  if (enable_extensions) {
    brave_browser_importer_impl_sources += [
      "//BnesBrowser/browser/importer/extensions_import_helpers.cc",
      "//BnesBrowser/browser/importer/extensions_import_helpers.h",
    ]
    brave_browser_importer_impl_deps += [
      "//BnesBrowser/common/importer",
      "//chrome/browser/extensions",
      "//components/value_store",
      "//extensions/browser",
      "//extensions/browser:webstore_installer",
      "//extensions/common:common_constants",
    ]
  }
  brave_browser_importer_impl_deps += [
    "//base",
    "//BnesBrowser/app:brave_generated_resources_grit_grit",
    "//BnesBrowser/browser/importer",
    "//BnesBrowser/common/importer",
    "//BnesBrowser/common/importer:interfaces",
    "//BnesBrowser/components/brave_origin/buildflags",
    "//chrome/browser:browser_process",
    "//chrome/browser/password_manager/factories",
    "//components/keyed_service/core",
    "//components/os_crypt/async/browser",
    "//components/os_crypt/async/common",
    "//components/password_manager/core/browser/password_store:password_store_impl",
    "//components/password_manager/core/browser/password_store:password_store_interface",
    "//content/public/browser",
    "//extensions/buildflags",
    "//mojo/public/cpp/bindings",
  ]
}
