# Copyright (c) 2020 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

import("//BnesBrowser/components/ai_chat/core/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/commander/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/omnibox/buildflags/buildflags.gni")

brave_components_omnibox_browser_sources = [
  "//BnesBrowser/components/omnibox/browser/brave_bookmark_provider.cc",
  "//BnesBrowser/components/omnibox/browser/brave_bookmark_provider.h",
  "//BnesBrowser/components/omnibox/browser/brave_history_quick_provider.cc",
  "//BnesBrowser/components/omnibox/browser/brave_history_quick_provider.h",
  "//BnesBrowser/components/omnibox/browser/brave_history_url_provider.cc",
  "//BnesBrowser/components/omnibox/browser/brave_history_url_provider.h",
  "//BnesBrowser/components/omnibox/browser/brave_local_history_zero_suggest_provider.cc",
  "//BnesBrowser/components/omnibox/browser/brave_local_history_zero_suggest_provider.h",
  "//BnesBrowser/components/omnibox/browser/brave_omnibox_prefs.cc",
  "//BnesBrowser/components/omnibox/browser/brave_omnibox_prefs.h",
  "//BnesBrowser/components/omnibox/browser/brave_on_device_head_provider.cc",
  "//BnesBrowser/components/omnibox/browser/brave_on_device_head_provider.h",
  "//BnesBrowser/components/omnibox/browser/brave_search_provider.cc",
  "//BnesBrowser/components/omnibox/browser/brave_search_provider.h",
  "//BnesBrowser/components/omnibox/browser/brave_search_suggestion_parser.cc",
  "//BnesBrowser/components/omnibox/browser/brave_search_suggestion_parser.h",
  "//BnesBrowser/components/omnibox/browser/brave_shortcuts_provider.cc",
  "//BnesBrowser/components/omnibox/browser/brave_shortcuts_provider.h",
  "//BnesBrowser/components/omnibox/browser/open_here_action.cc",
  "//BnesBrowser/components/omnibox/browser/open_here_action.h",
  "//BnesBrowser/components/omnibox/browser/promotion_provider.cc",
  "//BnesBrowser/components/omnibox/browser/promotion_provider.h",
  "//BnesBrowser/components/omnibox/browser/promotion_utils.cc",
  "//BnesBrowser/components/omnibox/browser/promotion_utils.h",
]

brave_components_omnibox_browser_deps = [
  "//base",
  "//BnesBrowser/components/brave_search_conversion",
  "//BnesBrowser/components/constants",
  "//BnesBrowser/components/omnibox/buildflags",
  "//BnesBrowser/components/resources:strings",
  "//BnesBrowser/components/vector_icons",
  "//components/prefs",
  "//components/vector_icons",
  "//url",
]

brave_components_omnibox_browser_public_deps = [
  "//BnesBrowser/components/ai_chat/core/common/buildflags",
  "//BnesBrowser/components/commander/common/buildflags",
]

if (enable_ai_chat) {
  brave_components_omnibox_browser_sources += [
    "//BnesBrowser/components/omnibox/browser/leo_action.cc",
    "//BnesBrowser/components/omnibox/browser/leo_action.h",
    "//BnesBrowser/components/omnibox/browser/leo_provider.cc",
    "//BnesBrowser/components/omnibox/browser/leo_provider.h",
  ]

  brave_components_omnibox_browser_deps += [
    "//BnesBrowser/components/ai_chat/core/browser",
    "//BnesBrowser/components/ai_chat/core/common",
  ]
}

if (enable_commander) {
  brave_components_omnibox_browser_sources += [
    "//BnesBrowser/components/omnibox/browser/commander_action.cc",
    "//BnesBrowser/components/omnibox/browser/commander_action.h",
    "//BnesBrowser/components/omnibox/browser/commander_provider.cc",
    "//BnesBrowser/components/omnibox/browser/commander_provider.h",
  ]

  brave_components_omnibox_browser_deps +=
      [ "//BnesBrowser/components/commander/browser" ]
}

if (enable_strict_query_check_for_search_suggestions) {
  brave_components_omnibox_browser_deps +=
      [ "//BnesBrowser/components/omnibox/browser/search_suggestions" ]
}
