# Copyright (c) 2024 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//BnesBrowser/components/brave_talk/buildflags/buildflags.gni")
import("//BnesBrowser/components/brave_wallet/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/playlist/core/common/buildflags/buildflags.gni")

source_set("web") {
  sources = [
    "brave_web_client.h",
    "brave_web_client.mm",
    "brave_web_main_parts.h",
    "brave_web_main_parts.mm",
  ]
  deps = [
    "//base",
    "//BnesBrowser/components/ai_chat/core/browser",
    "//BnesBrowser/components/brave_component_updater/browser:public",
    "//BnesBrowser/components/brave_shields/core/common",
    "//BnesBrowser/components/brave_talk/buildflags",
    "//BnesBrowser/components/brave_user_agent/browser",
    "//BnesBrowser/components/brave_wallet/common/buildflags",
    "//BnesBrowser/components/constants",
    "//BnesBrowser/components/global_privacy_control",
    "//BnesBrowser/components/playlist/core/common/buildflags",
    "//BnesBrowser/components/query_filter/browser",
    "//BnesBrowser/components/query_filter/common",
    "//BnesBrowser/ios/browser/ai_chat",
    "//BnesBrowser/ios/browser/api/profile",
    "//BnesBrowser/ios/browser/api/web_view",
    "//BnesBrowser/ios/browser/application_context",
    "//BnesBrowser/ios/browser/brave_ads",
    "//BnesBrowser/ios/browser/brave_search",
    "//BnesBrowser/ios/browser/brave_shields",
    "//BnesBrowser/ios/browser/brave_shields/cosmetic_filtering",
    "//BnesBrowser/ios/browser/brave_shields/request_blocking",
    "//BnesBrowser/ios/browser/component_updater:zxcvbn_data_component_installer",
    "//BnesBrowser/ios/browser/global_privacy_control",
    "//BnesBrowser/ios/browser/playlist",
    "//BnesBrowser/ios/browser/skus",
    "//BnesBrowser/ios/browser/ui/web_view:features",
    "//BnesBrowser/ios/browser/web/de_amp",
    "//BnesBrowser/ios/browser/web/document_fetch",
    "//BnesBrowser/ios/browser/web/force_paste",
    "//BnesBrowser/ios/browser/web/fullscreen",
    "//BnesBrowser/ios/browser/web/logins",
    "//BnesBrowser/ios/browser/web/media",
    "//BnesBrowser/ios/browser/web/navigator",
    "//BnesBrowser/ios/browser/web/night_mode",
    "//BnesBrowser/ios/browser/web/page_metadata",
    "//BnesBrowser/ios/browser/web/reader_mode",
    "//BnesBrowser/ios/browser/youtube",
    "//BnesBrowser/ios/web/js_messaging",
    "//components/component_updater/installer_policies",
    "//components/language/ios/browser",
    "//components/prefs",
    "//components/translate/ios/browser",
    "//ios/chrome/browser/application_context/model",
    "//ios/chrome/browser/shared/model/application_context",
    "//ios/chrome/browser/shared/model/paths",
    "//ios/chrome/browser/shared/model/profile",
    "//ios/chrome/browser/shared/model/url",
    "//ios/chrome/browser/shared/model/url:constants",
    "//ios/chrome/browser/web/model:web_internal",
    "//ios/chrome/browser/web/model/print",
    "//ios/components/security_interstitials",
    "//ios/components/security_interstitials/lookalikes",
    "//ios/components/security_interstitials/safe_browsing",
    "//ios/components/webui:url_constants",
    "//ios/public/provider/chrome/browser/url_rewriters:url_rewriters_api",
    "//ios/web_view/framework:web_view_sources",
  ]
  if (enable_brave_talk) {
    deps += [ "//BnesBrowser/ios/browser/brave_talk" ]
  }
  if (enable_brave_wallet) {
    deps += [
      "//BnesBrowser/components/brave_wallet/browser",
      "//BnesBrowser/ios/browser/brave_wallet",
    ]
  }
  if (enable_playlist) {
    deps += [
      "//BnesBrowser/components/playlist/core/browser",
      "//BnesBrowser/components/playlist/core/common",
    ]
  }
  frameworks = [ "Foundation.framework" ]
}
