# Copyright (c) 2026 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at https://mozilla.org/MPL/2.0/.

import("//BnesBrowser/components/brave_news/common/buildflags/buildflags.gni")

assert(enable_brave_news)
assert(!is_android)

source_set("brave_news") {
  sources = [
    "brave_news_ui.cc",
    "brave_news_ui.h",
  ]

  deps = [
    "//BnesBrowser/browser/brave_news",
    "//BnesBrowser/components/brave_news/browser",
    "//BnesBrowser/components/brave_news/browser/resources:sidebar_generated_resources",
    "//BnesBrowser/components/brave_news/common",
    "//BnesBrowser/components/brave_news/common:mojom",
    "//BnesBrowser/components/constants",
    "//BnesBrowser/components/resources:static_resources_grit",
    "//BnesBrowser/components/resources:strings",
    "//chrome/browser/ui/webui:theme_source",
    "//chrome/browser/ui/webui/top_chrome",
    "//content/public/browser",
    "//content/public/common",
    "//mojo/public/cpp/bindings",
    "//ui/webui",
  ]
}
