# Copyright (c) 2021 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

import("//BnesBrowser/components/ai_chat/core/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/brave_vpn/common/buildflags/buildflags.gni")
import("//BnesBrowser/components/local_ai/buildflags/buildflags.gni")
import("//BnesBrowser/components/text_recognition/common/buildflags/buildflags.gni")
import("//build/config/ui.gni")
import("//extensions/buildflags/buildflags.gni")

brave_chromium_src_chrome_browser_deps = [
  "//base",
  "//BnesBrowser/components/ai_chat/core/common/buildflags",
  "//BnesBrowser/components/brave_vpn/common/buildflags",
  "//BnesBrowser/components/commander/common/buildflags",
  "//BnesBrowser/components/local_ai/buildflags",
  "//BnesBrowser/components/playlist/core/common/buildflags",
  "//BnesBrowser/components/text_recognition/common/buildflags",
  "//chrome/common:channel_info",
  "//components/version_info",
]

if (!is_android) {
  brave_chromium_src_chrome_browser_deps += [ "//chrome/browser/ui" ]
}

if (enable_brave_vpn) {
  brave_chromium_src_chrome_browser_deps +=
      [ "//BnesBrowser/components/brave_vpn/common" ]
}

if (toolkit_views) {
  brave_chromium_src_chrome_browser_deps +=
      [ "//BnesBrowser/components/sidebar/browser" ]
}

if (enable_extensions) {
  brave_chromium_src_chrome_browser_deps +=
      [ "//BnesBrowser/browser/extensions/manifest_v2" ]
}
