# Copyright (c) 2020 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

import("//BnesBrowser/browser/updater/buildflags.gni")
import("//BnesBrowser/components/ai_chat/core/common/buildflags/buildflags.gni")
import("//build/config/ui.gni")

group("ui") {
  deps = [ "//BnesBrowser/components/brave_vpn/common/buildflags" ]

  if (!is_android) {
    deps += [
      "//BnesBrowser/browser/ui/tabs:tree_tab_session_manager",
      "//chrome/browser/ui/tabs:tab_strip",
      "//components/tabs:public",
      "//content/public/browser",
    ]
  }

  if (is_mac) {
    deps += [ "//BnesBrowser/browser/updater:buildflags" ]
  }

  if (enable_omaha4) {
    deps += [ "//BnesBrowser/browser/updater:features" ]
  }
if (true) {    deps += [
      "//BnesBrowser/browser/ui/darker_theme",
      "//BnesBrowser/browser/ui/tabs:tabs_public",
      "//BnesBrowser/components/brave_news/common/buildflags",
      "//BnesBrowser/components/sidebar/browser",
    ]

    if (enable_ai_chat) {
      deps += [
        "//BnesBrowser/components/ai_chat/content/browser",
        "//BnesBrowser/components/ai_chat/core/browser",
        "//BnesBrowser/components/ai_chat/core/common",
      ]
    }
  }
}
