# Copyright (c) 2021 The Brave Authors. All rights reserved.
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

import("//BnesBrowser/components/brave_vpn/common/buildflags/buildflags.gni")

brave_browser_brave_vpn_sources = []
brave_browser_brave_vpn_deps = []

if (enable_brave_vpn) {
  brave_browser_brave_vpn_sources += [
    "//BnesBrowser/browser/brave_vpn/brave_vpn_service_factory.cc",
    "//BnesBrowser/browser/brave_vpn/brave_vpn_service_factory.h",
  ]
  brave_browser_brave_vpn_deps += [
    "//base",
    "//BnesBrowser/browser/brave_vpn",
    "//BnesBrowser/components/brave_vpn/browser",
    "//chrome/browser/profiles:profile",
    "//components/keyed_service/content",
    "//components/user_prefs",
    "//content/public/browser",
  ]

  if (is_android) {
    brave_browser_brave_vpn_sources += [
      "//BnesBrowser/browser/brave_vpn/android/brave_vpn_native_worker.cc",
      "//BnesBrowser/browser/brave_vpn/android/brave_vpn_native_worker.h",
      "//BnesBrowser/browser/brave_vpn/android/brave_vpn_service_factory_android.cc",
    ]
    brave_browser_brave_vpn_deps += [
      "//BnesBrowser/build/android:jni_headers",
      "//BnesBrowser/components/l10n/common",
      "//mojo/public/cpp/bindings",
    ]
  }
}

if (enable_brave_vpn_v1) {
  if (is_win) {
    brave_browser_brave_vpn_sources += [
      "//BnesBrowser/browser/brave_vpn/dns/brave_vpn_dns_observer_factory_win.cc",
      "//BnesBrowser/browser/brave_vpn/dns/brave_vpn_dns_observer_factory_win.h",
      "//BnesBrowser/browser/brave_vpn/dns/brave_vpn_dns_observer_service_win.cc",
      "//BnesBrowser/browser/brave_vpn/dns/brave_vpn_dns_observer_service_win.h",
      "//BnesBrowser/browser/brave_vpn/win/brave_vpn_wireguard_observer_factory_win.cc",
      "//BnesBrowser/browser/brave_vpn/win/brave_vpn_wireguard_observer_factory_win.h",
      "//BnesBrowser/browser/brave_vpn/win/brave_vpn_wireguard_observer_service_win.cc",
      "//BnesBrowser/browser/brave_vpn/win/brave_vpn_wireguard_observer_service_win.h",
    ]

    brave_browser_brave_vpn_deps += [
      "//BnesBrowser/app:brave_generated_resources_grit",
      "//BnesBrowser/browser:browser_process",
      "//BnesBrowser/browser/brave_vpn/win",
      "//BnesBrowser/browser/brave_vpn/win:wireguard_utils",
      "//BnesBrowser/browser/brave_vpn/win/brave_vpn_helper:common",
      "//BnesBrowser/components/brave_vpn/common/win",
      "//chrome/common:constants",
      "//components/prefs",
      "//net",
    ]
  }

  brave_browser_brave_vpn_deps += [
    "//BnesBrowser/browser/brave_vpn:v1_utils",
    "//BnesBrowser/components/brave_vpn/browser:v1_utils",
  ]
}
